#!/usr/bin/env python3
"""Publish course materials from ``materials/`` to the ``website/``.

Usage::

    python publish.py                   # publish every lesson in publish.yml
    python publish.py physics           # publish only the physics lesson
    python publish.py physics biology   # publish several

For each lesson this (1) builds the LaTeX worksheet into the student and teacher
PDFs named in ``publish.yml`` (student = ``\\teacherfalse``, teacher =
``\\teachertrue``), and (2) copies every other material file (notebooks, code,
slides, images, ...) into the matching ``website/for-teachers`` lesson folder.

The files under ``materials/`` are the masters you edit. The copies under
``website/`` are generated by this script, so do not edit those by hand.
"""
from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent
CFG = yaml.safe_load((ROOT / "publish.yml").read_text(encoding="utf-8"))
PART = CFG["part"]
LESSONS = CFG["lessons"]
MATERIALS = ROOT / "materials" / PART
WEBSITE = ROOT / "website" / "for-teachers" / PART

SKIP_EXT = {".tex"}
LATEX_ARTIFACTS = {
    ".aux", ".log", ".out", ".toc", ".synctex.gz", ".fls",
    ".fdb_latexmk", ".nav", ".snm", ".vrb", ".bbl", ".blg",
}


def find_pdflatex() -> str:
    exe = shutil.which("pdflatex")
    if exe:
        return exe
    local = os.environ.get("LOCALAPPDATA", "")
    if local:
        for p in Path(local).glob("Programs/MiKTeX/miktex/bin/*/pdflatex.exe"):
            return str(p)
    raise SystemExit("pdflatex not found (install a TeX distribution or add it to PATH)")


def build_latex(lesson: str, spec: dict) -> None:
    src = MATERIALS / lesson
    tex = spec["tex"]
    dest_dir = WEBSITE / lesson
    dest_dir.mkdir(parents=True, exist_ok=True)
    pdflatex = find_pdflatex()
    for toggle, key in ((r"\teacherfalse", "student"), (r"\teachertrue", "teacher")):
        out_name = spec[key]
        with tempfile.TemporaryDirectory() as td:
            td = Path(td)
            for item in src.iterdir():
                if item.is_dir():
                    shutil.copytree(item, td / item.name)
                else:
                    shutil.copy2(item, td / item.name)
            texpath = td / tex
            text = texpath.read_text(encoding="utf-8")
            # function replacement: avoids re interpreting "\t" etc. in the toggle
            text = re.sub(r"\\teacher(?:true|false)", lambda _m: toggle, text)
            texpath.write_text(text, encoding="utf-8")
            for _ in range(2):  # twice, so cross-references resolve
                subprocess.run(
                    [pdflatex, "-interaction=nonstopmode", "-halt-on-error", tex],
                    cwd=td, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                )
            built = td / (Path(tex).stem + ".pdf")
            if not built.exists():
                raise SystemExit(f"  FAILED to build {lesson}/{tex} ({key})")
            shutil.copy2(built, dest_dir / out_name)
            print(f"  built  {lesson}: {out_name}")


def copy_materials(lesson: str) -> None:
    src = MATERIALS / lesson
    dest_dir = WEBSITE / lesson
    for dirpath, dirnames, filenames in os.walk(src):
        dp = Path(dirpath)
        if "Figures" in dp.relative_to(src).parts:   # LaTeX input only
            continue
        if "Figures" in dirnames:
            dirnames.remove("Figures")
        for fn in filenames:
            ext = Path(fn).suffix.lower()
            if ext in SKIP_EXT or ext in LATEX_ARTIFACTS:
                continue
            rel = (dp / fn).relative_to(src)
            target = dest_dir / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(dp / fn, target)
            print(f"  copied {lesson}: {rel.as_posix()}")


def main() -> None:
    want = sys.argv[1:] or list(LESSONS)
    unknown = [lsn for lsn in want if lsn not in LESSONS]
    if unknown:
        raise SystemExit(f"unknown lesson(s): {unknown}; known: {list(LESSONS)}")
    for lesson in want:
        print(f"[{lesson}]")
        spec = LESSONS[lesson]
        if "latex" in spec:
            build_latex(lesson, spec["latex"])
        copy_materials(lesson)
    print("done.")


if __name__ == "__main__":
    main()
